2018-01-07 18:05:30,011 https://slack.com:443 "POST /api/users.list HTTP/1.1" 200 1178
2018-01-07 18:05:30,107 Problem in Plugin Class: APICall: process_message 
{'type': 'message', 'channel': 'C8Q02AD1U', 'user': 'U8NE6R2TS', 'text': 'resync_member', 'ts': '1515323127.000032', 'source_team': 'T8NE6R2SU', 'team': 'T8NE6R2SU'}
Traceback (most recent call last):
  File "d:\Python36\lib\site-packages\rtmbot\core.py", line 205, in do
    func(data)
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 208, in process_message
    self.check_point()
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 56, in check_point
    print("updated_at:", datetime.strptime(member["updated_at"], "%Y-%m-%d"))
AttributeError: module 'datetime' has no attribute 'strptime'
2018-01-07 18:05:31,121 got process_pong
2018-01-07 18:05:35,150 got process_pong
2018-01-07 18:05:39,175 got process_pong
2018-01-07 18:05:43,197 got process_pong
2018-01-07 18:05:47,129 got process_pong
2018-01-07 18:05:51,156 got process_pong
2018-01-07 18:05:55,384 got process_pong
2018-01-07 18:05:59,113 got process_pong
2018-01-07 18:06:03,146 got process_pong
2018-01-07 18:06:07,188 got process_pong
2018-01-07 18:07:08,914 Initialized in: D:\Python36\Scripts\rtm5l4ckb0t
2018-01-07 18:07:08,930 Starting new HTTPS connection (1): slack.com
2018-01-07 18:07:10,713 https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 5225
2018-01-07 18:07:11,030 Loading plugins
2018-01-07 18:07:11,038 Importing plugins.directAPIcall.APICall
2018-01-07 18:07:11,089 Plugin registered: <plugins.directAPIcall.APICall object at 0x03428BD0>
2018-01-07 18:07:11,092 Registering jobs for APICall
2018-01-07 18:07:11,102 No jobs registered for APICall
2018-01-07 18:07:11,517 got process_hello
2018-01-07 18:07:15,147 got process_pong
2018-01-07 18:07:16,363 got process_user_typing
2018-01-07 18:07:16,776 got process_message
2018-01-07 18:07:16,802 Starting new HTTPS connection (1): slack.com
2018-01-07 18:07:17,932 https://slack.com:443 "POST /api/users.list HTTP/1.1" 200 1178
2018-01-07 18:07:18,022 Problem in Plugin Class: APICall: process_message 
{'type': 'message', 'channel': 'C8Q02AD1U', 'user': 'U8NE6R2TS', 'text': 'resync_member', 'ts': '1515323235.000035', 'source_team': 'T8NE6R2SU', 'team': 'T8NE6R2SU'}
Traceback (most recent call last):
  File "d:\Python36\lib\site-packages\rtmbot\core.py", line 205, in do
    func(data)
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 208, in process_message
    self.check_point()
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 56, in check_point
    print("updated_at:", datetime.datetime.strptime(member["updated_at"], "%Y-%m-%d"))
TypeError: strptime() argument 1 must be str, not datetime.datetime
2018-01-07 18:07:19,138 got process_pong
2018-01-07 18:07:23,165 got process_pong
2018-01-07 18:07:27,187 got process_pong
2018-01-07 18:07:31,129 got process_pong
2018-01-07 18:07:35,175 got process_pong
2018-01-07 18:07:39,203 got process_pong
2018-01-07 18:07:43,133 got process_pong
2018-01-07 18:07:47,167 got process_pong
2018-01-07 18:07:51,195 got process_pong
2018-01-07 18:07:55,116 got process_pong
2018-01-07 18:07:59,151 got process_pong
2018-01-07 18:08:03,179 got process_pong
2018-01-07 18:08:07,108 got process_pong
2018-01-07 18:08:11,142 got process_pong
2018-01-07 18:08:16,980 Initialized in: D:\Python36\Scripts\rtm5l4ckb0t
2018-01-07 18:08:16,991 Starting new HTTPS connection (1): slack.com
2018-01-07 18:08:18,553 https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 5227
2018-01-07 18:08:18,909 Loading plugins
2018-01-07 18:08:18,910 Importing plugins.directAPIcall.APICall
2018-01-07 18:08:18,943 Plugin registered: <plugins.directAPIcall.APICall object at 0x034888B0>
2018-01-07 18:08:18,944 Registering jobs for APICall
2018-01-07 18:08:18,945 No jobs registered for APICall
2018-01-07 18:08:19,452 got process_hello
2018-01-07 18:08:22,182 got process_pong
2018-01-07 18:08:23,102 got process_user_typing
2018-01-07 18:08:23,412 got process_message
2018-01-07 18:08:23,429 Starting new HTTPS connection (1): slack.com
2018-01-07 18:08:23,938 https://slack.com:443 "POST /api/users.list HTTP/1.1" 200 1178
2018-01-07 18:08:24,084 Problem in Plugin Class: APICall: process_message 
{'type': 'message', 'channel': 'C8Q02AD1U', 'user': 'U8NE6R2TS', 'text': 'resync_member', 'ts': '1515323301.000074', 'source_team': 'T8NE6R2SU', 'team': 'T8NE6R2SU'}
Traceback (most recent call last):
  File "d:\Python36\lib\site-packages\rtmbot\core.py", line 205, in do
    func(data)
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 209, in process_message
    self.check_point()
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 56, in check_point
    var_update_at=datetime.datetime.strptime(str(member["updated_at"]), "%Y-%m-%d")
  File "d:\Python36\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "d:\Python36\lib\_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:  17:59:10.649000
2018-01-07 18:08:26,112 got process_pong
2018-01-07 18:08:30,133 got process_pong
2018-01-07 18:08:34,155 got process_pong
2018-01-07 18:08:38,174 got process_pong
2018-01-07 18:08:42,197 got process_pong
2018-01-07 18:08:46,129 got process_pong
2018-01-07 18:08:50,162 got process_pong
2018-01-07 18:08:54,195 got process_pong
2018-01-07 18:13:27,178 Initialized in: D:\Python36\Scripts\rtm5l4ckb0t
2018-01-07 18:13:27,192 Starting new HTTPS connection (1): slack.com
2018-01-07 18:13:28,968 https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 5223
2018-01-07 18:13:29,340 Loading plugins
2018-01-07 18:13:29,350 Importing plugins.directAPIcall.APICall
2018-01-07 18:13:29,393 Plugin registered: <plugins.directAPIcall.APICall object at 0x03968BD0>
2018-01-07 18:13:29,394 Registering jobs for APICall
2018-01-07 18:13:29,397 No jobs registered for APICall
2018-01-07 18:13:29,907 got process_hello
2018-01-07 18:13:33,133 got process_pong
2018-01-07 18:13:35,660 got process_user_typing
2018-01-07 18:13:35,975 got process_message
2018-01-07 18:13:35,990 Starting new HTTPS connection (1): slack.com
2018-01-07 18:13:36,911 https://slack.com:443 "POST /api/users.list HTTP/1.1" 200 1178
2018-01-07 18:13:37,025 Problem in Plugin Class: APICall: process_message 
{'type': 'message', 'channel': 'C8Q02AD1U', 'user': 'U8NE6R2TS', 'text': 'resync_member', 'ts': '1515323614.000041', 'source_team': 'T8NE6R2SU', 'team': 'T8NE6R2SU'}
Traceback (most recent call last):
  File "d:\Python36\lib\site-packages\rtmbot\core.py", line 205, in do
    func(data)
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 209, in process_message
    self.check_point()
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 59, in check_point
    diff = today - member["updated_at"]
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'
2018-01-07 18:13:37,138 got process_pong
2018-01-07 18:13:41,172 got process_pong
2018-01-07 18:13:45,204 got process_pong
2018-01-07 18:58:39,047 Initialized in: D:\Python36\Scripts\rtm5l4ckb0t
2018-01-07 18:58:39,060 Starting new HTTPS connection (1): slack.com
2018-01-07 18:58:40,803 https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 5227
2018-01-07 18:58:41,189 Loading plugins
2018-01-07 18:58:41,190 Importing plugins.directAPIcall.APICall
2018-01-07 18:59:23,286 Initialized in: D:\Python36\Scripts\rtm5l4ckb0t
2018-01-07 18:59:23,301 Starting new HTTPS connection (1): slack.com
2018-01-07 18:59:24,742 https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 5226
2018-01-07 18:59:25,117 Loading plugins
2018-01-07 18:59:25,124 Importing plugins.directAPIcall.APICall
2018-01-07 18:59:25,165 Plugin registered: <plugins.directAPIcall.APICall object at 0x02FE3A70>
2018-01-07 18:59:25,169 Registering jobs for APICall
2018-01-07 18:59:25,172 No jobs registered for APICall
2018-01-07 18:59:25,678 got process_hello
2018-01-07 18:59:29,194 got process_pong
2018-01-07 18:59:32,809 got process_user_typing
2018-01-07 18:59:33,118 got process_pong
2018-01-07 18:59:33,625 got process_message
2018-01-07 18:59:33,641 Starting new HTTPS connection (1): slack.com
2018-01-07 18:59:34,555 https://slack.com:443 "POST /api/users.list HTTP/1.1" 200 1178
2018-01-07 18:59:34,634 Problem in Plugin Class: APICall: process_message 
{'type': 'message', 'channel': 'C8Q02AD1U', 'user': 'U8NE6R2TS', 'text': 'resync_member', 'ts': '1515326372.000041', 'source_team': 'T8NE6R2SU', 'team': 'T8NE6R2SU'}
Traceback (most recent call last):
  File "d:\Python36\lib\site-packages\rtmbot\core.py", line 205, in do
    func(data)
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 216, in process_message
    self.check_point()
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 66, in check_point
    diff = today - update_formated
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'str'
2018-01-07 18:59:37,150 got process_pong
2018-01-07 18:59:41,163 got process_pong
2018-01-07 18:59:45,182 got process_pong
2018-01-07 18:59:49,206 got process_pong
2018-01-07 18:59:53,124 got process_pong
2018-01-07 18:59:57,137 got process_pong
2018-01-07 19:00:01,152 got process_pong
2018-01-07 19:00:05,168 got process_pong
2018-01-07 19:00:09,180 got process_pong
2018-01-07 19:00:13,202 got process_pong
2018-01-07 19:00:17,115 got process_pong
2018-01-07 19:00:21,125 got process_pong
2018-01-07 19:00:25,140 got process_pong
2018-01-07 19:00:29,155 got process_pong
2018-01-07 19:00:33,165 got process_pong
2018-01-07 19:00:36,974 Initialized in: D:\Python36\Scripts\rtm5l4ckb0t
2018-01-07 19:00:36,989 Starting new HTTPS connection (1): slack.com
2018-01-07 19:00:38,793 https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 5224
2018-01-07 19:00:39,139 Loading plugins
2018-01-07 19:00:39,144 Importing plugins.directAPIcall.APICall
2018-01-07 19:00:39,176 Plugin registered: <plugins.directAPIcall.APICall object at 0x03623A70>
2018-01-07 19:00:39,177 Registering jobs for APICall
2018-01-07 19:00:39,178 No jobs registered for APICall
2018-01-07 19:00:39,690 got process_hello
2018-01-07 19:00:43,107 got process_pong
2018-01-07 19:00:43,815 got process_message
2018-01-07 19:00:43,831 Starting new HTTPS connection (1): slack.com
2018-01-07 19:00:44,952 https://slack.com:443 "POST /api/users.list HTTP/1.1" 200 1178
2018-01-07 19:00:45,023 Problem in Plugin Class: APICall: process_message 
{'type': 'message', 'channel': 'C8Q02AD1U', 'user': 'U8NE6R2TS', 'text': 'resync_member', 'ts': '1515326442.000058', 'source_team': 'T8NE6R2SU', 'team': 'T8NE6R2SU'}
Traceback (most recent call last):
  File "d:\Python36\lib\site-packages\rtmbot\core.py", line 205, in do
    func(data)
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 216, in process_message
    self.check_point()
  File "D:\Python36\Scripts\rtm5l4ckb0t\plugins\directAPIcall.py", line 59, in check_point
    my_time = datetime.datetime.strptime(updated_at, "%Y-%m-%d %H:%M:%S.%f")
TypeError: strptime() argument 1 must be str, not datetime.datetime
2018-01-07 19:00:47,141 got process_pong
